name: release

on:
  push:
    branches: [ master ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Make temporary directory
        run: mkdir temp/
        
      - name: Make temporary artifacts directory
        run: mkdir temp/artifacts/
        
      - name: Install LESS compiler
        run: npm i less -g
        
      - name: Compile LESS
        run: lessc dist/less/bootstrap-multiselect.less temp/bootstrap-multiselect.css
        
      - name: Minify CSS
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: "temp/bootstrap-multiselect.css"
          output: "temp/artifacts/"
          
      - name: Minify JS
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: "dist/js/bootstrap-multiselect.js"
          output: "temp/artifacts/"
          
      - name: test
        run: ls temp/artifacts
        
      - name: test
        run: ls temp
